use std::path::{Path, PathBuf};
use std::process::Command;

use crate::error::{Error, Result};

/// Download Jenkins agent.jar from the controller.
pub fn download_agent_jar(controller_url: &str, dest: &Path) -> Result<()> {
    if let Some(parent) = dest.parent() {
        std::fs::create_dir_all(parent).map_err(|e| {
            Error::Config(format!("failed to create {}: {e}", parent.display()))
        })?;
    }
    let url = format!(
        "{}/jnlpJars/agent.jar",
        controller_url.trim_end_matches('/')
    );
    println!("Downloading agent.jar from {url}");
    let status = Command::new("curl")
        .args(["-fsSL", "-o", &dest.display().to_string(), &url])
        .status()
        .map_err(|e| Error::CommandFailed {
            cmd: format!("curl {url}"),
            source: e.into(),
        })?;
    if !status.success() {
        return Err(Error::CommandFailed {
            cmd: format!("curl {url}"),
            source: anyhow::anyhow!("exit {:?}", status.code()),
        });
    }
    Ok(())
}

/// Write a launch script for the inbound agent (secret filled after registration).
pub fn write_launch_script(
    script_path: &Path,
    controller_url: &str,
    agent_name: &str,
    agent_jar: &Path,
    secret_placeholder: &str,
) -> Result<()> {
    if let Some(parent) = script_path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| {
            Error::Config(format!("failed to create {}: {e}", parent.display()))
        })?;
    }
    let body = format!(
        r#"#!/usr/bin/env bash
set -euo pipefail
# Generated by mac-k3d prepare — replace SECRET if registration was manual.
exec java -jar "{jar}" \
  -url "{url}" \
  -secret "{secret}" \
  -name "{name}" \
  -webSocket
"#,
        jar = agent_jar.display(),
        url = controller_url.trim_end_matches('/'),
        secret = secret_placeholder,
        name = agent_name,
    );
    std::fs::write(script_path, body).map_err(|e| {
        Error::Config(format!("failed to write {}: {e}", script_path.display()))
    })?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(script_path)
            .map_err(|e| Error::Config(e.to_string()))?
            .permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(script_path, perms)
            .map_err(|e| Error::Config(e.to_string()))?;
    }
    Ok(())
}

/// Register node via Jenkins REST API when token is available.
///
/// Returns Ok(Some(secret)) when registration succeeded, Ok(None) when skipped
/// (no token) or when create succeeded but secret could not be parsed.
pub fn try_register_node(
    controller_url: &str,
    agent_name: &str,
    remote_fs: &Path,
    labels: &[String],
    api_user: Option<&str>,
    api_token: Option<&str>,
) -> Result<Option<String>> {
    let (Some(user), Some(token)) = (api_user, api_token) else {
        println!(
            "\nNo Jenkins API token provided — skipping auto-registration.\n\
             Create a Permanent Agent named '{agent_name}' on the controller, then run the launch script.\n\
             Labels: {}\n\
             Remote root: {}\n\
             Controller: {controller_url}\n",
            labels.join(" "),
            remote_fs.display()
        );
        return Ok(None);
    };

    let base = controller_url.trim_end_matches('/');
    let auth = format!("{user}:{token}");
    let labels_joined = labels.join(" ");

    let crumb = fetch_crumb(base, &auth);

    // Skip create if node already exists.
    let exists = curl_status(base, &auth, &format!("/computer/{agent_name}/api/json"), &crumb)
        .map(|c| c == 200)
        .unwrap_or(false);

    if !exists {
        let xml = agent_config_xml(agent_name, remote_fs, &labels_joined);
        let create_url = format!(
            "{base}/computer/doCreateItem?name={}&type=hudson.slaves.DumbSlave",
            urlencoding_simple(agent_name)
        );
        println!("Registering Jenkins agent '{agent_name}' on {base} …");
        let mut cmd = Command::new("curl");
        cmd.args([
            "-sS",
            "-o",
            "/dev/null",
            "-w",
            "%{http_code}",
            "-u",
            &auth,
            "-H",
            "Content-Type: application/xml",
            "-X",
            "POST",
            &create_url,
            "--data-binary",
            &xml,
        ]);
        if let Some((field, value)) = &crumb {
            cmd.args(["-H", &format!("{field}: {value}")]);
        }
        let output = cmd.output().map_err(|e| Error::CommandFailed {
            cmd: "curl doCreateItem".into(),
            source: e.into(),
        })?;
        let code = String::from_utf8_lossy(&output.stdout).trim().to_string();
        if code != "200" && code != "302" && code != "303" {
            println!(
                "Warning: failed to create agent via API (HTTP {code}). Create the node in the UI, then paste the secret into the launch script."
            );
            return Ok(None);
        }
    } else {
        println!("Jenkins agent '{agent_name}' already exists on controller.");
    }

    match fetch_jnlp_secret(base, &auth, agent_name, &crumb) {
        Some(secret) => {
            println!("Retrieved agent connection secret.");
            Ok(Some(secret))
        }
        None => {
            println!(
                "Agent created (or already present), but could not parse JNLP secret.\n\
                 Open {base}/computer/{agent_name}/ and copy the secret into the launch script."
            );
            Ok(None)
        }
    }
}

fn agent_config_xml(name: &str, remote_fs: &Path, labels: &str) -> String {
    format!(
        r#"<?xml version='1.1' encoding='UTF-8'?>
<slave>
  <name>{name}</name>
  <description>mac-k3d worker agent</description>
  <remoteFS>{remote}</remoteFS>
  <numExecutors>1</numExecutors>
  <mode>NORMAL</mode>
  <retentionStrategy class="hudson.slaves.RetentionStrategy$Always"/>
  <launcher class="hudson.slaves.JNLPLauncher">
    <workDirSettings>
      <disabled>false</disabled>
      <internalDir>remoting</internalDir>
      <failIfWorkDirIsMissing>false</failIfWorkDirIsMissing>
    </workDirSettings>
    <webSocket>true</webSocket>
  </launcher>
  <label>{labels}</label>
  <nodeProperties/>
</slave>
"#,
        remote = remote_fs.display(),
    )
}

fn fetch_crumb(base: &str, auth: &str) -> Option<(String, String)> {
    let output = Command::new("curl")
        .args(["-fsS", "-u", auth, &format!("{base}/crumbIssuer/api/json")])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let text = String::from_utf8_lossy(&output.stdout);
    let field = extract_json_str(&text, "crumbRequestField")?;
    let crumb = extract_json_str(&text, "crumb")?;
    Some((field, crumb))
}

fn curl_status(base: &str, auth: &str, path: &str, crumb: &Option<(String, String)>) -> Option<i32> {
    let mut args = vec![
        "-sS".into(),
        "-o".into(),
        "/dev/null".into(),
        "-w".into(),
        "%{http_code}".into(),
        "-u".into(),
        auth.to_string(),
        format!("{base}{path}"),
    ];
    if let Some((field, value)) = crumb {
        args.push("-H".into());
        args.push(format!("{field}: {value}"));
    }
    let output = Command::new("curl").args(&args).output().ok()?;
    String::from_utf8_lossy(&output.stdout).trim().parse().ok()
}

fn fetch_jnlp_secret(
    base: &str,
    auth: &str,
    agent_name: &str,
    crumb: &Option<(String, String)>,
) -> Option<String> {
    let mut cmd = Command::new("curl");
    cmd.args(["-fsS", "-u", auth, &format!("{base}/computer/{agent_name}/slave-agent.jnlp")]);
    if let Some((field, value)) = crumb {
        cmd.args(["-H", &format!("{field}: {value}")]);
    }
    let output = cmd.output().ok()?;
    if !output.status.success() {
        return None;
    }
    let text = String::from_utf8_lossy(&output.stdout);
    // <argument>-secret</argument><argument>HEX</argument> or <secret>HEX</secret>
    if let Some(idx) = text.find("<secret>") {
        let rest = &text[idx + "<secret>".len()..];
        let end = rest.find("</secret>")?;
        return Some(rest[..end].trim().to_string());
    }
    if let Some(idx) = text.find("-secret</argument>") {
        let after = &text[idx + "-secret</argument>".len()..];
        let start = after.find("<argument>")? + "<argument>".len();
        let end = after[start..].find("</argument>")? + start;
        return Some(after[start..end].trim().to_string());
    }
    None
}

fn extract_json_str(json: &str, key: &str) -> Option<String> {
    let needle = format!("\"{key}\"");
    let idx = json.find(&needle)?;
    let after = &json[idx + needle.len()..];
    let colon = after.find(':')?;
    let rest = after[colon + 1..].trim_start();
    if !rest.starts_with('"') {
        return None;
    }
    let rest = &rest[1..];
    let end = rest.find('"')?;
    Some(rest[..end].to_string())
}

fn urlencoding_simple(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            'A'..='Z' | 'a'..='z' | '0'..='9' | '-' | '_' | '.' | '~' => c.to_string(),
            _ => format!("%{:02X}", c as u8),
        })
        .collect()
}

pub fn default_agent_name() -> String {
    let host = Command::new("hostname")
        .arg("-s")
        .output()
        .ok()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "mac".into());
    format!("mac-{host}")
}

pub fn default_remote_fs() -> PathBuf {
    std::env::var_os("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."))
        .join("jenkins-agent")
}
