use std::path::{Path, PathBuf};
use std::process::Command;

use crate::error::{Error, Result};

/// Download Jenkins agent.jar from the controller.
pub fn download_agent_jar(controller_url: &str, dest: &Path) -> Result<()> {
    if let Some(parent) = dest.parent() {
        std::fs::create_dir_all(parent).map_err(|e| {
            Error::Config(format!("failed to create {}: {e}", parent.display()))
        })?;
    }
    let url = format!(
        "{}/jnlpJars/agent.jar",
        controller_url.trim_end_matches('/')
    );
    println!("Downloading agent.jar from {url}");
    let status = Command::new("curl")
        .args(["-fsSL", "-o", &dest.display().to_string(), &url])
        .status()
        .map_err(|e| Error::CommandFailed {
            cmd: format!("curl {url}"),
            source: e.into(),
        })?;
    if !status.success() {
        return Err(Error::CommandFailed {
            cmd: format!("curl {url}"),
            source: anyhow::anyhow!("exit {:?}", status.code()),
        });
    }
    Ok(())
}

/// Write a launch script for the inbound agent (secret filled after registration).
pub fn write_launch_script(
    script_path: &Path,
    controller_url: &str,
    agent_name: &str,
    agent_jar: &Path,
    secret_placeholder: &str,
) -> Result<()> {
    write_launch_script_with_java(
        script_path,
        controller_url,
        agent_name,
        agent_jar,
        secret_placeholder,
        "java",
    )
}

pub fn write_launch_script_with_java(
    script_path: &Path,
    controller_url: &str,
    agent_name: &str,
    agent_jar: &Path,
    secret_placeholder: &str,
    java_bin: &str,
) -> Result<()> {
    if let Some(parent) = script_path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| {
            Error::Config(format!("failed to create {}: {e}", parent.display()))
        })?;
    }
    let body = format!(
        r#"#!/usr/bin/env bash
set -euo pipefail
# Generated by mac-k3d — replace SECRET if registration was manual.
exec "{java}" -jar "{jar}" \
  -url "{url}" \
  -secret "{secret}" \
  -name "{name}" \
  -webSocket
"#,
        java = java_bin,
        jar = agent_jar.display(),
        url = controller_url.trim_end_matches('/'),
        secret = secret_placeholder,
        name = agent_name,
    );
    std::fs::write(script_path, body).map_err(|e| {
        Error::Config(format!("failed to write {}: {e}", script_path.display()))
    })?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(script_path)
            .map_err(|e| Error::Config(e.to_string()))?
            .permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(script_path, perms)
            .map_err(|e| Error::Config(e.to_string()))?;
    }
    Ok(())
}

/// Register node via Jenkins REST API when token is available.
///
/// Returns Ok(Some(secret)) when registration succeeded, Ok(None) when skipped
/// (no token) or when create succeeded but secret could not be parsed.
pub fn try_register_node(
    controller_url: &str,
    agent_name: &str,
    remote_fs: &Path,
    labels: &[String],
    api_user: Option<&str>,
    api_token: Option<&str>,
) -> Result<Option<String>> {
    let (Some(user), Some(token)) = (api_user, api_token) else {
        println!(
            "\nNo Jenkins API token provided — skipping auto-registration.\n\
             Create a Permanent Agent named '{agent_name}' on the controller, then run the launch script.\n\
             Labels: {}\n\
             Remote root: {}\n\
             Controller: {controller_url}\n",
            labels.join(" "),
            remote_fs.display()
        );
        return Ok(None);
    };

    let base = controller_url.trim_end_matches('/');
    let auth = format!("{user}:{token}");
    let labels_joined = labels.join(" ");

    let cookie_file = tempfile_path("mac-k3d-jenkins-cookies")?;
    let crumb = fetch_crumb(base, &auth, &cookie_file);

    // Skip create if node already exists.
    let exists = curl_status(base, &auth, &format!("/computer/{agent_name}/api/json"), &crumb, &cookie_file)
        .map(|c| c == 200)
        .unwrap_or(false);

    if !exists {
        let xml = agent_config_xml(agent_name, remote_fs, &labels_joined);
        // Modern Jenkins: POST /computer/createItem?name=… with XML body.
        // (doCreateItem expects a Stapler form submission and returns HTTP 400 for raw XML.)
        let create_url = format!(
            "{base}/computer/createItem?name={}",
            urlencoding_simple(agent_name)
        );
        println!("Registering Jenkins agent '{agent_name}' on {base} …");
        let mut cmd = Command::new("curl");
        cmd.args([
            "-sS",
            "-b",
            &cookie_file.display().to_string(),
            "-c",
            &cookie_file.display().to_string(),
            "-u",
            &auth,
            "-H",
            "Content-Type: application/xml",
            "-X",
            "POST",
            &create_url,
            "--data-binary",
            &xml,
            "-w",
            "\n%{http_code}",
        ]);
        if let Some((field, value)) = &crumb {
            cmd.args(["-H", &format!("{field}: {value}")]);
        }
        let output = cmd.output().map_err(|e| Error::CommandFailed {
            cmd: "curl computer/createItem".into(),
            source: e.into(),
        })?;
        let raw = String::from_utf8_lossy(&output.stdout);
        let code = raw.lines().last().unwrap_or("").trim().to_string();
        if code != "200" && code != "201" && code != "302" && code != "303" {
            let body: String = raw
                .lines()
                .rev()
                .skip(1)
                .collect::<Vec<_>>()
                .into_iter()
                .rev()
                .collect::<Vec<_>>()
                .join("\n");
            let snippet: String = body.chars().take(240).collect();
            println!(
                "Warning: failed to create agent via API (HTTP {code}). {snippet}\n\
                 Create the node in the UI, then paste the secret into the launch script."
            );
            let _ = std::fs::remove_file(&cookie_file);
            return Ok(None);
        }
    } else {
        println!("Jenkins agent '{agent_name}' already exists on controller.");
    }

    let secret = fetch_jnlp_secret(base, &auth, agent_name, &crumb, &cookie_file);
    let _ = std::fs::remove_file(&cookie_file);

    match secret {
        Some(secret) => {
            println!("Retrieved agent connection secret.");
            Ok(Some(secret))
        }
        None => {
            println!(
                "Agent created (or already present), but could not parse JNLP secret.\n\
                 Open {base}/computer/{agent_name}/ and copy the secret into the launch script."
            );
            Ok(None)
        }
    }
}

fn agent_config_xml(name: &str, remote_fs: &Path, labels: &str) -> String {
    format!(
        r#"<?xml version='1.1' encoding='UTF-8'?>
<slave>
  <name>{name}</name>
  <description>mac-k3d worker agent</description>
  <remoteFS>{remote}</remoteFS>
  <numExecutors>1</numExecutors>
  <mode>NORMAL</mode>
  <retentionStrategy class="hudson.slaves.RetentionStrategy$Always"/>
  <launcher class="hudson.slaves.JNLPLauncher">
    <workDirSettings>
      <disabled>false</disabled>
      <internalDir>remoting</internalDir>
      <failIfWorkDirIsMissing>false</failIfWorkDirIsMissing>
    </workDirSettings>
    <webSocket>true</webSocket>
  </launcher>
  <label>{labels}</label>
  <nodeProperties/>
</slave>
"#,
        remote = remote_fs.display(),
    )
}

fn tempfile_path(prefix: &str) -> Result<PathBuf> {
    let dir = std::env::temp_dir();
    let path = dir.join(format!("{prefix}-{}", std::process::id()));
    // Ensure file exists for curl -c
    std::fs::File::create(&path).map_err(|e| Error::Config(e.to_string()))?;
    Ok(path)
}

fn fetch_crumb(base: &str, auth: &str, cookie_file: &Path) -> Option<(String, String)> {
    let output = Command::new("curl")
        .args([
            "-fsS",
            "-b",
            &cookie_file.display().to_string(),
            "-c",
            &cookie_file.display().to_string(),
            "-u",
            auth,
            &format!("{base}/crumbIssuer/api/json"),
        ])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let text = String::from_utf8_lossy(&output.stdout);
    let field = extract_json_str(&text, "crumbRequestField")?;
    let crumb = extract_json_str(&text, "crumb")?;
    Some((field, crumb))
}

fn curl_status(
    base: &str,
    auth: &str,
    path: &str,
    crumb: &Option<(String, String)>,
    cookie_file: &Path,
) -> Option<i32> {
    let mut args = vec![
        "-sS".into(),
        "-o".into(),
        "/dev/null".into(),
        "-w".into(),
        "%{http_code}".into(),
        "-b".into(),
        cookie_file.display().to_string(),
        "-c".into(),
        cookie_file.display().to_string(),
        "-u".into(),
        auth.to_string(),
        format!("{base}{path}"),
    ];
    if let Some((field, value)) = crumb {
        args.push("-H".into());
        args.push(format!("{field}: {value}"));
    }
    let output = Command::new("curl").args(&args).output().ok()?;
    String::from_utf8_lossy(&output.stdout).trim().parse().ok()
}

fn fetch_jnlp_secret(
    base: &str,
    auth: &str,
    agent_name: &str,
    crumb: &Option<(String, String)>,
    cookie_file: &Path,
) -> Option<String> {
    let mut cmd = Command::new("curl");
    cmd.args([
        "-fsS",
        "-b",
        &cookie_file.display().to_string(),
        "-c",
        &cookie_file.display().to_string(),
        "-u",
        auth,
        &format!("{base}/computer/{agent_name}/slave-agent.jnlp"),
    ]);
    if let Some((field, value)) = crumb {
        cmd.args(["-H", &format!("{field}: {value}")]);
    }
    let output = cmd.output().ok()?;
    if !output.status.success() {
        return None;
    }
    parse_jnlp_secret(&String::from_utf8_lossy(&output.stdout))
}

/// Parse inbound-agent secret from slave-agent.jnlp XML.
pub fn parse_jnlp_secret(text: &str) -> Option<String> {
    // Modern: <argument>SECRET</argument><argument>NAME</argument>…
    if let Some(idx) = text.find("<argument>") {
        let rest = &text[idx + "<argument>".len()..];
        let end = rest.find("</argument>")?;
        let first = rest[..end].trim();
        if !first.is_empty() && !first.starts_with('-') {
            return Some(first.to_string());
        }
    }
    // Legacy: <secret>HEX</secret>
    if let Some(idx) = text.find("<secret>") {
        let rest = &text[idx + "<secret>".len()..];
        let end = rest.find("</secret>")?;
        return Some(rest[..end].trim().to_string());
    }
    // Legacy: <argument>-secret</argument><argument>HEX</argument>
    if let Some(idx) = text.find("-secret</argument>") {
        let after = &text[idx + "-secret</argument>".len()..];
        let start = after.find("<argument>")? + "<argument>".len();
        let end = after[start..].find("</argument>")? + start;
        return Some(after[start..end].trim().to_string());
    }
    None
}

fn extract_json_str(json: &str, key: &str) -> Option<String> {
    let needle = format!("\"{key}\"");
    let idx = json.find(&needle)?;
    let after = &json[idx + needle.len()..];
    let colon = after.find(':')?;
    let rest = after[colon + 1..].trim_start();
    if !rest.starts_with('"') {
        return None;
    }
    let rest = &rest[1..];
    let end = rest.find('"')?;
    Some(rest[..end].to_string())
}

fn urlencoding_simple(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            'A'..='Z' | 'a'..='z' | '0'..='9' | '-' | '_' | '.' | '~' => c.to_string(),
            _ => format!("%{:02X}", c as u8),
        })
        .collect()
}

pub fn default_agent_name() -> String {
    let host = Command::new("hostname")
        .arg("-s")
        .output()
        .ok()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "mac".into());
    format!("mac-{host}")
}

pub fn default_remote_fs() -> PathBuf {
    std::env::var_os("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."))
        .join("jenkins-agent")
}

/// Download jar, register node (if credentials present), write launch script.
pub fn ensure_worker_agent(config: &crate::config::MacK3dConfig) -> Result<()> {
    use crate::config::NodeRole;
    use crate::prepare::resources;

    if !matches!(config.role, NodeRole::Worker) {
        return Ok(());
    }
    let Some(url) = config.jenkins_agent.controller_url.clone() else {
        return Ok(());
    };
    let name = config
        .jenkins_agent
        .name
        .clone()
        .unwrap_or_else(default_agent_name);
    let jar = config.jenkins_agent.agent_jar.clone().unwrap_or_else(|| {
        config
            .storage
            .downloads_dir()
            .unwrap_or_else(|| PathBuf::from("downloads"))
            .join("jenkins-agent")
            .join("agent.jar")
    });
    let remote_fs = config
        .jenkins_agent
        .remote_fs
        .clone()
        .unwrap_or_else(default_remote_fs);

    download_agent_jar(&url, &jar)?;

    let secret = try_register_node(
        &url,
        &name,
        &remote_fs,
        &config.jenkins_agent.labels,
        config.jenkins_agent.api_user.as_deref(),
        config.jenkins_agent.api_token.as_deref(),
    )?;
    let secret_placeholder = secret.unwrap_or_else(|| "REPLACE_ME".into());

    let java_bin = config
        .dependencies
        .java
        .binary
        .as_ref()
        .filter(|p| p.exists())
        .map(|p| p.display().to_string())
        .filter(|s| {
            // Prefer configured path only if it actually runs.
            std::process::Command::new(s)
                .arg("-version")
                .output()
                .map(|o| o.status.success())
                .unwrap_or(false)
        })
        .or_else(|| {
            crate::prepare::discovery::discover_all()
                .java
                .map(|t| t.binary.display().to_string())
        })
        .unwrap_or_else(|| "java".into());

    let script = remote_fs.join("launch-agent.sh");
    write_launch_script_with_java(
        &script,
        &url,
        &name,
        &jar,
        &secret_placeholder,
        &java_bin,
    )?;
    println!("Wrote agent launch script: {} (java: {java_bin})", script.display());
    if secret_placeholder != "REPLACE_ME" {
        println!("Start the agent with:\n  {}", script.display());
    }

    resources::register_agent_cpu_cores(
        &url,
        &name,
        &config.resources.cpu_cores_label,
        config.jenkins_agent.cpu_cores,
    )?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_modern_jnlp_secret() {
        let xml = r#"<jnlp><application-desc><argument>abc123secret</argument><argument>mac-host</argument><argument>-webSocket</argument></application-desc></jnlp>"#;
        assert_eq!(parse_jnlp_secret(xml).as_deref(), Some("abc123secret"));
    }

    #[test]
    fn parse_legacy_secret_tag() {
        let xml = r#"<jnlp><secret>deadbeef</secret></jnlp>"#;
        assert_eq!(parse_jnlp_secret(xml).as_deref(), Some("deadbeef"));
    }
}
